Improve + add job names
mondoohq/actions pull request #42
Opened 2022-11-16 23:08 UTC by tas50

Make sure these match what's happening

Signed-off-by: Tim Smith <tsmith84@gmail.com>

2022-11-17 00:55 UTC, scottford-io requested changes
@tas50 I love this! It was on my list as well, so THANK YOU!!!

I made some suggestions. I think we should provide names that are very descriptive. An example is that if we just use something like `scan-tf` for HCL, plan, and state jobs, then you would end up with three jobs that are named the same.

2022-11-17 00:55 UTC, scottford-io commented on terraform-plan/README.md
> +  scan-tf:
```suggestion
  terraform-plan-security-scan:
```

2022-11-17 00:55 UTC, scottford-io commented on terraform-hcl/README.md
> +  scan-tf:
```suggestion
  terraform-hcl-security-scan:
```

2022-11-17 00:55 UTC, scottford-io commented on terraform-state/README.md
> +  scan-tf:
```suggestion
  terraform-state-security-scan:
```

2022-11-17 00:55 UTC, scottford-io commented on README.md
>        - "k8s/*.yaml"
```suggestion
      - "k8s/manifest.yaml"
```

2022-11-17 00:55 UTC, scottford-io commented on README.md
> +  scan:
```suggestion
  k8s-manifest-scan:
```

2022-11-17 00:55 UTC, scottford-io commented on policy/README.md
> +  upload:
```suggestion
  upload-policy-bundle:
```

2022-11-29 21:15 UTC, merged

2022-11-29 21:15 UTC, tas50 commented
Merging after pulling in the suggestions from Scott